version: '3.9'
services:
  prometheus:
    image: prom/prometheus:latest
    networks:
      - monitoring
    user: root
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.config.file=/etc/prometheus/web.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    volumes:
      - ./configs/prom-config.yml:/etc/prometheus/prometheus.yml
      - ./metrics:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.prometheus.entrypoints=web"
        - "traefik.http.services.${STACK_NAME}_prometheus.loadbalancer.server.port=9090"
      restart_policy:
        condition: on-failure
      env_file:
        - ./configs/env

networks:
  monitoring: 
    external: true